### ISSUE TITLE
How to compile AndroratServer?

### ISSUE THREAD

**Issue by ma3axaka007** [wszf/androrat#8]
I installed Eclipse and i want to compile AndroratServer, but after importing AndroratServer in Eclipse and running it i get this
![2016-08-30_124116](https://cloud.githubusercontent.com/assets/9701284/18089363/a49f5882-6ed0-11e6-9c3b-984b8852c46e.png)

**Comment by ma3axaka007** [comment]
Where there are standart menus as showing in screenshots?

**Comment by ma3axaka007** [comment]
Soloved

**Comment by Axe-Usa** [comment]
How you solve the problem?
